#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 51
#define LARGE_STATE_COUNT 19
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_value = 1,
  sym_equals = 2,
  sym_segment_separator = 3,
  sym_single_quote = 4,
  sym_double_quote = 5,
  sym_open_curl = 6,
  sym_close_curl = 7,
  sym_open_bracket = 8,
  sym_close_bracket = 9,
  sym_open_paren = 10,
  sym_close_paren = 11,
  sym_back_tick = 12,
  sym_pathNode = 13,
  sym_segment = 14,
  sym_modelRef = 15,
  sym_query = 16,
  sym_expression = 17,
  aux_sym_pathNode_repeat1 = 18,
  aux_sym_segment_repeat1 = 19,
  aux_sym_expression_repeat1 = 20,
  aux_sym_expression_repeat2 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_value] = "value",
  [sym_equals] = "equals",
  [sym_segment_separator] = "segment_separator",
  [sym_single_quote] = "single_quote",
  [sym_double_quote] = "double_quote",
  [sym_open_curl] = "open_curl",
  [sym_close_curl] = "close_curl",
  [sym_open_bracket] = "open_bracket",
  [sym_close_bracket] = "close_bracket",
  [sym_open_paren] = "open_paren",
  [sym_close_paren] = "close_paren",
  [sym_back_tick] = "back_tick",
  [sym_pathNode] = "pathNode",
  [sym_segment] = "segment",
  [sym_modelRef] = "modelRef",
  [sym_query] = "query",
  [sym_expression] = "expression",
  [aux_sym_pathNode_repeat1] = "pathNode_repeat1",
  [aux_sym_segment_repeat1] = "segment_repeat1",
  [aux_sym_expression_repeat1] = "expression_repeat1",
  [aux_sym_expression_repeat2] = "expression_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_value] = sym_value,
  [sym_equals] = sym_equals,
  [sym_segment_separator] = sym_segment_separator,
  [sym_single_quote] = sym_single_quote,
  [sym_double_quote] = sym_double_quote,
  [sym_open_curl] = sym_open_curl,
  [sym_close_curl] = sym_close_curl,
  [sym_open_bracket] = sym_open_bracket,
  [sym_close_bracket] = sym_close_bracket,
  [sym_open_paren] = sym_open_paren,
  [sym_close_paren] = sym_close_paren,
  [sym_back_tick] = sym_back_tick,
  [sym_pathNode] = sym_pathNode,
  [sym_segment] = sym_segment,
  [sym_modelRef] = sym_modelRef,
  [sym_query] = sym_query,
  [sym_expression] = sym_expression,
  [aux_sym_pathNode_repeat1] = aux_sym_pathNode_repeat1,
  [aux_sym_segment_repeat1] = aux_sym_segment_repeat1,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
  [aux_sym_expression_repeat2] = aux_sym_expression_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_equals] = {
    .visible = true,
    .named = true,
  },
  [sym_segment_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_open_curl] = {
    .visible = true,
    .named = true,
  },
  [sym_close_curl] = {
    .visible = true,
    .named = true,
  },
  [sym_open_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_close_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_open_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_close_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_back_tick] = {
    .visible = true,
    .named = true,
  },
  [sym_pathNode] = {
    .visible = true,
    .named = true,
  },
  [sym_segment] = {
    .visible = true,
    .named = true,
  },
  [sym_modelRef] = {
    .visible = true,
    .named = true,
  },
  [sym_query] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_pathNode_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_segment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 4,
  [8] = 3,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      ADVANCE_MAP(
        '"', 6,
        '\'', 5,
        '(', 11,
        ')', 12,
        '.', 4,
        '=', 3,
        '[', 9,
        ']', 10,
        '`', 13,
        '{', 7,
        '}', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(sym_value);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_equals);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_segment_separator);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_single_quote);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_double_quote);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_open_curl);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_close_curl);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_open_bracket);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_close_bracket);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_open_paren);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_close_paren);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_back_tick);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_value] = ACTIONS(1),
    [sym_equals] = ACTIONS(1),
    [sym_segment_separator] = ACTIONS(1),
    [sym_single_quote] = ACTIONS(1),
    [sym_double_quote] = ACTIONS(1),
    [sym_open_curl] = ACTIONS(1),
    [sym_close_curl] = ACTIONS(1),
    [sym_open_bracket] = ACTIONS(1),
    [sym_close_bracket] = ACTIONS(1),
    [sym_open_paren] = ACTIONS(1),
    [sym_close_paren] = ACTIONS(1),
    [sym_back_tick] = ACTIONS(1),
  },
  [1] = {
    [sym_pathNode] = STATE(48),
    [sym_segment] = STATE(36),
    [sym_modelRef] = STATE(7),
    [sym_query] = STATE(7),
    [sym_expression] = STATE(7),
    [sym_value] = ACTIONS(3),
    [sym_single_quote] = ACTIONS(5),
    [sym_double_quote] = ACTIONS(7),
    [sym_open_curl] = ACTIONS(9),
    [sym_open_bracket] = ACTIONS(11),
    [sym_back_tick] = ACTIONS(13),
  },
  [2] = {
    [sym_segment] = STATE(2),
    [sym_modelRef] = STATE(4),
    [sym_query] = STATE(4),
    [sym_expression] = STATE(4),
    [aux_sym_segment_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_value] = ACTIONS(17),
    [sym_equals] = ACTIONS(15),
    [sym_segment_separator] = ACTIONS(15),
    [sym_single_quote] = ACTIONS(20),
    [sym_double_quote] = ACTIONS(23),
    [sym_open_curl] = ACTIONS(26),
    [sym_close_curl] = ACTIONS(15),
    [sym_open_bracket] = ACTIONS(29),
    [sym_close_bracket] = ACTIONS(15),
    [sym_open_paren] = ACTIONS(15),
    [sym_close_paren] = ACTIONS(15),
    [sym_back_tick] = ACTIONS(32),
  },
  [3] = {
    [sym_segment] = STATE(2),
    [sym_modelRef] = STATE(4),
    [sym_query] = STATE(4),
    [sym_expression] = STATE(4),
    [aux_sym_segment_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_value] = ACTIONS(35),
    [sym_equals] = ACTIONS(35),
    [sym_segment_separator] = ACTIONS(35),
    [sym_single_quote] = ACTIONS(35),
    [sym_double_quote] = ACTIONS(35),
    [sym_open_curl] = ACTIONS(35),
    [sym_close_curl] = ACTIONS(35),
    [sym_open_bracket] = ACTIONS(35),
    [sym_close_bracket] = ACTIONS(35),
    [sym_open_paren] = ACTIONS(35),
    [sym_close_paren] = ACTIONS(35),
    [sym_back_tick] = ACTIONS(35),
  },
  [4] = {
    [sym_segment] = STATE(3),
    [sym_modelRef] = STATE(4),
    [sym_query] = STATE(4),
    [sym_expression] = STATE(4),
    [aux_sym_segment_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_value] = ACTIONS(37),
    [sym_equals] = ACTIONS(37),
    [sym_segment_separator] = ACTIONS(37),
    [sym_single_quote] = ACTIONS(37),
    [sym_double_quote] = ACTIONS(37),
    [sym_open_curl] = ACTIONS(37),
    [sym_close_curl] = ACTIONS(37),
    [sym_open_bracket] = ACTIONS(37),
    [sym_close_bracket] = ACTIONS(37),
    [sym_open_paren] = ACTIONS(37),
    [sym_close_paren] = ACTIONS(37),
    [sym_back_tick] = ACTIONS(37),
  },
  [5] = {
    [sym_segment] = STATE(28),
    [sym_modelRef] = STATE(4),
    [sym_query] = STATE(4),
    [sym_expression] = STATE(4),
    [aux_sym_expression_repeat2] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(39),
    [sym_value] = ACTIONS(39),
    [sym_equals] = ACTIONS(39),
    [sym_segment_separator] = ACTIONS(39),
    [sym_single_quote] = ACTIONS(39),
    [sym_double_quote] = ACTIONS(39),
    [sym_open_curl] = ACTIONS(39),
    [sym_close_curl] = ACTIONS(39),
    [sym_open_bracket] = ACTIONS(39),
    [sym_close_bracket] = ACTIONS(39),
    [sym_open_paren] = ACTIONS(39),
    [sym_close_paren] = ACTIONS(39),
    [sym_back_tick] = ACTIONS(39),
  },
  [6] = {
    [sym_segment] = STATE(28),
    [sym_modelRef] = STATE(4),
    [sym_query] = STATE(4),
    [sym_expression] = STATE(4),
    [aux_sym_expression_repeat2] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym_value] = ACTIONS(41),
    [sym_equals] = ACTIONS(41),
    [sym_segment_separator] = ACTIONS(41),
    [sym_single_quote] = ACTIONS(41),
    [sym_double_quote] = ACTIONS(41),
    [sym_open_curl] = ACTIONS(41),
    [sym_close_curl] = ACTIONS(41),
    [sym_open_bracket] = ACTIONS(41),
    [sym_close_bracket] = ACTIONS(41),
    [sym_open_paren] = ACTIONS(41),
    [sym_close_paren] = ACTIONS(41),
    [sym_back_tick] = ACTIONS(41),
  },
  [7] = {
    [sym_segment] = STATE(8),
    [sym_modelRef] = STATE(4),
    [sym_query] = STATE(4),
    [sym_expression] = STATE(4),
    [aux_sym_segment_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_value] = ACTIONS(43),
    [sym_segment_separator] = ACTIONS(37),
    [sym_single_quote] = ACTIONS(5),
    [sym_double_quote] = ACTIONS(7),
    [sym_open_curl] = ACTIONS(9),
    [sym_close_curl] = ACTIONS(37),
    [sym_open_bracket] = ACTIONS(11),
    [sym_close_bracket] = ACTIONS(37),
    [sym_close_paren] = ACTIONS(37),
    [sym_back_tick] = ACTIONS(13),
  },
  [8] = {
    [sym_segment] = STATE(2),
    [sym_modelRef] = STATE(4),
    [sym_query] = STATE(4),
    [sym_expression] = STATE(4),
    [aux_sym_segment_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_value] = ACTIONS(43),
    [sym_segment_separator] = ACTIONS(35),
    [sym_single_quote] = ACTIONS(5),
    [sym_double_quote] = ACTIONS(7),
    [sym_open_curl] = ACTIONS(9),
    [sym_close_curl] = ACTIONS(35),
    [sym_open_bracket] = ACTIONS(11),
    [sym_close_bracket] = ACTIONS(35),
    [sym_close_paren] = ACTIONS(35),
    [sym_back_tick] = ACTIONS(13),
  },
  [9] = {
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym_value] = ACTIONS(45),
    [sym_equals] = ACTIONS(45),
    [sym_segment_separator] = ACTIONS(45),
    [sym_single_quote] = ACTIONS(45),
    [sym_double_quote] = ACTIONS(45),
    [sym_open_curl] = ACTIONS(45),
    [sym_close_curl] = ACTIONS(45),
    [sym_open_bracket] = ACTIONS(45),
    [sym_close_bracket] = ACTIONS(45),
    [sym_open_paren] = ACTIONS(45),
    [sym_close_paren] = ACTIONS(45),
    [sym_back_tick] = ACTIONS(45),
  },
  [10] = {
    [ts_builtin_sym_end] = ACTIONS(47),
    [sym_value] = ACTIONS(47),
    [sym_equals] = ACTIONS(47),
    [sym_segment_separator] = ACTIONS(47),
    [sym_single_quote] = ACTIONS(47),
    [sym_double_quote] = ACTIONS(47),
    [sym_open_curl] = ACTIONS(47),
    [sym_close_curl] = ACTIONS(47),
    [sym_open_bracket] = ACTIONS(47),
    [sym_close_bracket] = ACTIONS(47),
    [sym_open_paren] = ACTIONS(47),
    [sym_close_paren] = ACTIONS(47),
    [sym_back_tick] = ACTIONS(47),
  },
  [11] = {
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym_value] = ACTIONS(49),
    [sym_equals] = ACTIONS(49),
    [sym_segment_separator] = ACTIONS(49),
    [sym_single_quote] = ACTIONS(49),
    [sym_double_quote] = ACTIONS(49),
    [sym_open_curl] = ACTIONS(49),
    [sym_close_curl] = ACTIONS(49),
    [sym_open_bracket] = ACTIONS(49),
    [sym_close_bracket] = ACTIONS(49),
    [sym_open_paren] = ACTIONS(49),
    [sym_close_paren] = ACTIONS(49),
    [sym_back_tick] = ACTIONS(49),
  },
  [12] = {
    [ts_builtin_sym_end] = ACTIONS(51),
    [sym_value] = ACTIONS(51),
    [sym_equals] = ACTIONS(51),
    [sym_segment_separator] = ACTIONS(51),
    [sym_single_quote] = ACTIONS(51),
    [sym_double_quote] = ACTIONS(51),
    [sym_open_curl] = ACTIONS(51),
    [sym_close_curl] = ACTIONS(51),
    [sym_open_bracket] = ACTIONS(51),
    [sym_close_bracket] = ACTIONS(51),
    [sym_open_paren] = ACTIONS(51),
    [sym_close_paren] = ACTIONS(51),
    [sym_back_tick] = ACTIONS(51),
  },
  [13] = {
    [ts_builtin_sym_end] = ACTIONS(53),
    [sym_value] = ACTIONS(53),
    [sym_equals] = ACTIONS(53),
    [sym_segment_separator] = ACTIONS(53),
    [sym_single_quote] = ACTIONS(53),
    [sym_double_quote] = ACTIONS(53),
    [sym_open_curl] = ACTIONS(53),
    [sym_close_curl] = ACTIONS(53),
    [sym_open_bracket] = ACTIONS(53),
    [sym_close_bracket] = ACTIONS(53),
    [sym_open_paren] = ACTIONS(53),
    [sym_close_paren] = ACTIONS(53),
    [sym_back_tick] = ACTIONS(53),
  },
  [14] = {
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym_value] = ACTIONS(55),
    [sym_equals] = ACTIONS(55),
    [sym_segment_separator] = ACTIONS(55),
    [sym_single_quote] = ACTIONS(55),
    [sym_double_quote] = ACTIONS(55),
    [sym_open_curl] = ACTIONS(55),
    [sym_close_curl] = ACTIONS(55),
    [sym_open_bracket] = ACTIONS(55),
    [sym_close_bracket] = ACTIONS(55),
    [sym_open_paren] = ACTIONS(55),
    [sym_close_paren] = ACTIONS(55),
    [sym_back_tick] = ACTIONS(55),
  },
  [15] = {
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym_value] = ACTIONS(57),
    [sym_equals] = ACTIONS(57),
    [sym_segment_separator] = ACTIONS(57),
    [sym_single_quote] = ACTIONS(57),
    [sym_double_quote] = ACTIONS(57),
    [sym_open_curl] = ACTIONS(57),
    [sym_close_curl] = ACTIONS(57),
    [sym_open_bracket] = ACTIONS(57),
    [sym_close_bracket] = ACTIONS(57),
    [sym_open_paren] = ACTIONS(57),
    [sym_close_paren] = ACTIONS(57),
    [sym_back_tick] = ACTIONS(57),
  },
  [16] = {
    [sym_segment] = STATE(41),
    [sym_modelRef] = STATE(7),
    [sym_query] = STATE(7),
    [sym_expression] = STATE(7),
    [sym_value] = ACTIONS(3),
    [sym_equals] = ACTIONS(59),
    [sym_single_quote] = ACTIONS(5),
    [sym_double_quote] = ACTIONS(7),
    [sym_open_curl] = ACTIONS(9),
    [sym_open_bracket] = ACTIONS(11),
    [sym_close_bracket] = ACTIONS(61),
    [sym_back_tick] = ACTIONS(13),
  },
  [17] = {
    [sym_segment] = STATE(40),
    [sym_modelRef] = STATE(7),
    [sym_query] = STATE(7),
    [sym_expression] = STATE(7),
    [sym_value] = ACTIONS(3),
    [sym_equals] = ACTIONS(63),
    [sym_single_quote] = ACTIONS(5),
    [sym_double_quote] = ACTIONS(7),
    [sym_open_curl] = ACTIONS(9),
    [sym_open_bracket] = ACTIONS(11),
    [sym_close_bracket] = ACTIONS(65),
    [sym_back_tick] = ACTIONS(13),
  },
  [18] = {
    [sym_segment] = STATE(46),
    [sym_modelRef] = STATE(7),
    [sym_query] = STATE(7),
    [sym_expression] = STATE(7),
    [sym_value] = ACTIONS(3),
    [sym_equals] = ACTIONS(67),
    [sym_single_quote] = ACTIONS(5),
    [sym_double_quote] = ACTIONS(7),
    [sym_open_curl] = ACTIONS(9),
    [sym_open_bracket] = ACTIONS(11),
    [sym_close_bracket] = ACTIONS(69),
    [sym_back_tick] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(5), 1,
      sym_single_quote,
    ACTIONS(7), 1,
      sym_double_quote,
    ACTIONS(9), 1,
      sym_open_curl,
    ACTIONS(11), 1,
      sym_open_bracket,
    ACTIONS(43), 1,
      sym_value,
    ACTIONS(71), 1,
      sym_back_tick,
    STATE(20), 1,
      aux_sym_expression_repeat2,
    STATE(28), 1,
      sym_segment,
    STATE(4), 3,
      sym_modelRef,
      sym_query,
      sym_expression,
  [30] = 9,
    ACTIONS(73), 1,
      sym_value,
    ACTIONS(76), 1,
      sym_single_quote,
    ACTIONS(79), 1,
      sym_double_quote,
    ACTIONS(82), 1,
      sym_open_curl,
    ACTIONS(85), 1,
      sym_open_bracket,
    ACTIONS(88), 1,
      sym_back_tick,
    STATE(20), 1,
      aux_sym_expression_repeat2,
    STATE(28), 1,
      sym_segment,
    STATE(4), 3,
      sym_modelRef,
      sym_query,
      sym_expression,
  [60] = 9,
    ACTIONS(3), 1,
      sym_value,
    ACTIONS(5), 1,
      sym_single_quote,
    ACTIONS(7), 1,
      sym_double_quote,
    ACTIONS(9), 1,
      sym_open_curl,
    ACTIONS(11), 1,
      sym_open_bracket,
    ACTIONS(13), 1,
      sym_back_tick,
    STATE(36), 1,
      sym_segment,
    STATE(43), 1,
      sym_pathNode,
    STATE(7), 3,
      sym_modelRef,
      sym_query,
      sym_expression,
  [90] = 9,
    ACTIONS(3), 1,
      sym_value,
    ACTIONS(5), 1,
      sym_single_quote,
    ACTIONS(7), 1,
      sym_double_quote,
    ACTIONS(9), 1,
      sym_open_curl,
    ACTIONS(11), 1,
      sym_open_bracket,
    ACTIONS(13), 1,
      sym_back_tick,
    ACTIONS(91), 1,
      sym_close_bracket,
    STATE(47), 1,
      sym_segment,
    STATE(7), 3,
      sym_modelRef,
      sym_query,
      sym_expression,
  [120] = 9,
    ACTIONS(3), 1,
      sym_value,
    ACTIONS(5), 1,
      sym_single_quote,
    ACTIONS(7), 1,
      sym_double_quote,
    ACTIONS(9), 1,
      sym_open_curl,
    ACTIONS(11), 1,
      sym_open_bracket,
    ACTIONS(13), 1,
      sym_back_tick,
    ACTIONS(93), 1,
      sym_close_paren,
    STATE(42), 1,
      sym_segment,
    STATE(7), 3,
      sym_modelRef,
      sym_query,
      sym_expression,
  [150] = 9,
    ACTIONS(5), 1,
      sym_single_quote,
    ACTIONS(7), 1,
      sym_double_quote,
    ACTIONS(9), 1,
      sym_open_curl,
    ACTIONS(11), 1,
      sym_open_bracket,
    ACTIONS(43), 1,
      sym_value,
    ACTIONS(95), 1,
      sym_back_tick,
    STATE(19), 1,
      aux_sym_expression_repeat2,
    STATE(28), 1,
      sym_segment,
    STATE(4), 3,
      sym_modelRef,
      sym_query,
      sym_expression,
  [180] = 8,
    ACTIONS(3), 1,
      sym_value,
    ACTIONS(5), 1,
      sym_single_quote,
    ACTIONS(7), 1,
      sym_double_quote,
    ACTIONS(9), 1,
      sym_open_curl,
    ACTIONS(11), 1,
      sym_open_bracket,
    ACTIONS(13), 1,
      sym_back_tick,
    STATE(37), 1,
      sym_segment,
    STATE(7), 3,
      sym_modelRef,
      sym_query,
      sym_expression,
  [207] = 8,
    ACTIONS(5), 1,
      sym_single_quote,
    ACTIONS(7), 1,
      sym_double_quote,
    ACTIONS(9), 1,
      sym_open_curl,
    ACTIONS(11), 1,
      sym_open_bracket,
    ACTIONS(13), 1,
      sym_back_tick,
    ACTIONS(43), 1,
      sym_value,
    STATE(16), 1,
      sym_segment,
    STATE(4), 3,
      sym_modelRef,
      sym_query,
      sym_expression,
  [234] = 4,
    ACTIONS(99), 1,
      sym_equals,
    ACTIONS(102), 1,
      sym_open_paren,
    STATE(27), 1,
      aux_sym_expression_repeat1,
    ACTIONS(97), 6,
      sym_value,
      sym_single_quote,
      sym_double_quote,
      sym_open_curl,
      sym_open_bracket,
      sym_back_tick,
  [252] = 4,
    ACTIONS(107), 1,
      sym_equals,
    ACTIONS(109), 1,
      sym_open_paren,
    STATE(29), 1,
      aux_sym_expression_repeat1,
    ACTIONS(105), 6,
      sym_value,
      sym_single_quote,
      sym_double_quote,
      sym_open_curl,
      sym_open_bracket,
      sym_back_tick,
  [270] = 4,
    ACTIONS(107), 1,
      sym_equals,
    ACTIONS(109), 1,
      sym_open_paren,
    STATE(27), 1,
      aux_sym_expression_repeat1,
    ACTIONS(111), 6,
      sym_value,
      sym_single_quote,
      sym_double_quote,
      sym_open_curl,
      sym_open_bracket,
      sym_back_tick,
  [288] = 2,
    ACTIONS(113), 1,
      sym_equals,
    ACTIONS(97), 7,
      sym_value,
      sym_single_quote,
      sym_double_quote,
      sym_open_curl,
      sym_open_bracket,
      sym_open_paren,
      sym_back_tick,
  [301] = 2,
    ACTIONS(118), 1,
      sym_equals,
    ACTIONS(116), 7,
      sym_value,
      sym_single_quote,
      sym_double_quote,
      sym_open_curl,
      sym_open_bracket,
      sym_open_paren,
      sym_back_tick,
  [314] = 1,
    ACTIONS(97), 8,
      sym_value,
      sym_equals,
      sym_single_quote,
      sym_double_quote,
      sym_open_curl,
      sym_open_bracket,
      sym_open_paren,
      sym_back_tick,
  [325] = 1,
    ACTIONS(121), 8,
      sym_value,
      sym_equals,
      sym_single_quote,
      sym_double_quote,
      sym_open_curl,
      sym_open_bracket,
      sym_open_paren,
      sym_back_tick,
  [336] = 3,
    ACTIONS(125), 1,
      sym_segment_separator,
    STATE(34), 1,
      aux_sym_pathNode_repeat1,
    ACTIONS(123), 2,
      ts_builtin_sym_end,
      sym_close_curl,
  [347] = 3,
    ACTIONS(130), 1,
      sym_segment_separator,
    STATE(34), 1,
      aux_sym_pathNode_repeat1,
    ACTIONS(128), 2,
      ts_builtin_sym_end,
      sym_close_curl,
  [358] = 3,
    ACTIONS(130), 1,
      sym_segment_separator,
    STATE(35), 1,
      aux_sym_pathNode_repeat1,
    ACTIONS(132), 2,
      ts_builtin_sym_end,
      sym_close_curl,
  [369] = 1,
    ACTIONS(123), 3,
      ts_builtin_sym_end,
      sym_segment_separator,
      sym_close_curl,
  [375] = 1,
    ACTIONS(134), 1,
      sym_close_curl,
  [379] = 1,
    ACTIONS(136), 1,
      sym_value,
  [383] = 1,
    ACTIONS(69), 1,
      sym_close_bracket,
  [387] = 1,
    ACTIONS(65), 1,
      sym_close_bracket,
  [391] = 1,
    ACTIONS(138), 1,
      sym_close_paren,
  [395] = 1,
    ACTIONS(140), 1,
      sym_close_curl,
  [399] = 1,
    ACTIONS(142), 1,
      sym_double_quote,
  [403] = 1,
    ACTIONS(142), 1,
      sym_single_quote,
  [407] = 1,
    ACTIONS(91), 1,
      sym_close_bracket,
  [411] = 1,
    ACTIONS(144), 1,
      sym_close_bracket,
  [415] = 1,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
  [419] = 1,
    ACTIONS(148), 1,
      sym_open_curl,
  [423] = 1,
    ACTIONS(150), 1,
      sym_value,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(19)] = 0,
  [SMALL_STATE(20)] = 30,
  [SMALL_STATE(21)] = 60,
  [SMALL_STATE(22)] = 90,
  [SMALL_STATE(23)] = 120,
  [SMALL_STATE(24)] = 150,
  [SMALL_STATE(25)] = 180,
  [SMALL_STATE(26)] = 207,
  [SMALL_STATE(27)] = 234,
  [SMALL_STATE(28)] = 252,
  [SMALL_STATE(29)] = 270,
  [SMALL_STATE(30)] = 288,
  [SMALL_STATE(31)] = 301,
  [SMALL_STATE(32)] = 314,
  [SMALL_STATE(33)] = 325,
  [SMALL_STATE(34)] = 336,
  [SMALL_STATE(35)] = 347,
  [SMALL_STATE(36)] = 358,
  [SMALL_STATE(37)] = 369,
  [SMALL_STATE(38)] = 375,
  [SMALL_STATE(39)] = 379,
  [SMALL_STATE(40)] = 383,
  [SMALL_STATE(41)] = 387,
  [SMALL_STATE(42)] = 391,
  [SMALL_STATE(43)] = 395,
  [SMALL_STATE(44)] = 399,
  [SMALL_STATE(45)] = 403,
  [SMALL_STATE(46)] = 407,
  [SMALL_STATE(47)] = 411,
  [SMALL_STATE(48)] = 415,
  [SMALL_STATE(49)] = 419,
  [SMALL_STATE(50)] = 423,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_segment_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_segment_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_segment_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_segment_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_segment_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_segment_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_segment_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_segment, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_segment, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 7, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 4, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 6, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 5, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modelRef, 5, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_segment, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 2, 0, 0), SHIFT_REPEAT(4),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 2, 0, 0), SHIFT_REPEAT(39),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 2, 0, 0), SHIFT_REPEAT(50),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 2, 0, 0), SHIFT_REPEAT(49),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 2, 0, 0), SHIFT_REPEAT(26),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 2, 0, 0), SHIFT_REPEAT(24),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 2, 0, 0),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 1, 0, 0),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 1, 0, 0), SHIFT_REPEAT(30),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pathNode_repeat1, 2, 0, 0),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pathNode_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pathNode, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pathNode, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [146] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_player_bindings(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
